# Generated by Django 3.2.6 on 2021-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_auto_20210908_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phoneNumber',
            field=models.CharField(default='08101234567', max_length=11),
            preserve_default=False,
        ),
    ]
