# Generated by Django 3.2.6 on 2021-09-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_participant_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2021-08-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
