# Generated by Django 3.2.6 on 2021-09-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_auto_20210908_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
    ]
